### ISSUE TITLE
Love the plugin. Few UI / UX suggestions

### ISSUE THREAD

**Issue by arunbasillal** [superwebshare/super-web-share#11]
Hello Jose, 

I started using Super Web Share on https://millionclues.com. Thanks for the plugin, loving it so far. Sending over few UI / UX suggestions. 

**Idea 1** - Display the share button in the WordPress admin area within Super Web Share settings. I mean here - https://jmp.sh/UidiYNam
- This will help previewing the button easier and users wouldn't have to visit the front end to verify colour / position. 
- I hope this isn't too complicated. Just need to confirm that the share button is loaded only in Super Web Share settings.

**Idea 2** - Combine button position into a single line. Would be cleaner I feel.

![image](https://user-images.githubusercontent.com/5751474/202101435-e6b13d76-2262-4d34-a098-dd60b01723aa.png)

**Idea 3** - Match the colour in the `Appearance` settings to the colour selected for button in the `Floating` Settings. Now the button uses the default colour regardless of the colour selected in the other settings.

![image](https://user-images.githubusercontent.com/5751474/202102584-9c8756b2-8ece-477a-9d95-a5486a9165fa.png)

**Idea 4** - When use selects a colour in the `Floating` settings, copy the same colour to button colour in `Inline content` settings and background colour in `Fallback` settings. Best to do this only the first time user save settings. 

The thought / assumption is that most users would want the same colour for all these options. They would first configure the `Floating` settings tab and save the settings. By the time they reach the other tabs they will have their chosen colour picked out for them. A better user experience imho.

**And one small UI bug** - Default colour in `Floating` and `Inline Content` settings is #000000. But in `Fallback` settings it is #bd3854. 

![image](https://user-images.githubusercontent.com/5751474/202102074-4fec8e13-3600-4bbc-8593-fb98e7409787.png)

Congrats on the plugin, keep up the good work. Looking forward to the premium version soon :)

**Comment by josevarghese** [comment]
Hi @arunbasillal 

Thanks a lot for sharing your feedback and pointing out the bug. I never expected that you would try this small plugin and install it on your website. Woo-Hoo!!! Thanks for that! :)

The reason why I am replying after some days is that I stopped checking the GitHub issues for the last few months, as I noticed that no one is really interested in opening an issue or sharing suggestions even after asking them to open an issue via the forum :D I noticed that most of them prefer to report issues via email or social channels as they prefer it to work more quickly than via GitHub, or else none of the developers who have GitHub accounts didn't try the plugin to report those.

Update: I[ just fixed the bug regarding the default color,](https://github.com/superwebshare/super-web-share/commit/428f70397a3466085a084d2b8a250820b3382a5b) and it will be rolled out within the next version.

I liked the ideas you've shared, and most of them are something that I missed and should be within the plugin to improve the experience.

**Suggestions 2, 3 & 4:** These can be implemented sometime. I will try to implement it in the upcoming versions.

**Idea 1:** I liked the idea, but the issue arises when the customer selects the button position as left and if the preview is set to show on the Right side. If the preview is set to show based on the position, there is a change for the button to appear above the settings. Most RTL language users prefer this left button as the position, and there's a chance to trigger some support tickets via it.

I plan to show a mobile preview by showing a mobile screen and button with some brandings for the plugin for this. Or to display these with some images within the configuration wizard pr settings (which is also within the pipeline, but the priority for it is currently set as very low as some features which I think would be more helpful are still on the pending board). Let's see how this can be improved in the future.

**Regarding Premium:** Some features for the premium version that other plugin lacks are on my board for the last couple of years, and I am confident with those features. But it will take more time for me to get it implemented, mostly due to the time constraints and another plugin that is in the development phase for the last few months. Need to sort it out :) 

Thanks again for your feedback, suggestions and for pointing out the bug. It means a lot to me. 🙏

**Comment by arunbasillal** [comment]
Thanks for the reply Jose and once again thanks for the plugin. I wanted to try your plugin for a while but never really got to doing it until now. Happy to see it growing.

> the issue arises when the customer selects the button position as left and if the preview is set to show on the Right side. If the preview is set to show based on the position, there is a change for the button to appear above the settings. Most RTL language users prefer this left button as the position, and there's a chance to trigger some support tickets via it.

This is a valid point and I didn't think of that. I agree with you :)
I think it's best to leave the preview to the front end based on this. 

Feel free to close the issue as you please if you have a different method to track suggestions. Looking forward to future versions.

**Comment by josevarghese** [comment]
Thank you again, Arun 😊🎉🚀

**Comment by arunbasillal** [comment]
Just updated to 2.4 and happy to see the suggestions implemented. Thank you so much :)

**Comment by josevarghese** [comment]
Good to hear it Arun :)
